### ISSUE TITLE
Windows7 Conflict

### ISSUE THREAD

**Issue by pedroalbanese** [jNizM/AHK_CNG#7]
Greetings!

I'm having trouble decrypting messages. I'm actually having problems compiling this script, with version 2.0 RC. I get error that Crypt.ahk is missing a comma.

The script partially runs on version 1.1, but I can't decrypt it.
```ahk
; #Requires AutoHotkey v2.0-
#NoEnv
#include Cryptv1.ahk
SetBatchLines, -1
Gui, Margin, 20, 10
Gui, Font, s10, Courier New
Gui, Add, Edit, w600 r10 vInput, %Dummy%
Gui, Font
Gui, Add, Button, gEncode, Encode
Gui, Add, Button, x+m yp gDecode, Decode
Gui, Add, edit, x180 y190 w180 h20 vKey, abcdef0123456789
Gui, Add, edit, x400 y190 w180 h20 vIV, abcdef0123456789
Gui, Font, s10, Courier New
Gui, Add, Edit, xm w600 r10 vResult +ReadOnly
Gui, Show, , EncryptGUI
Return

GuiClose:
ExitApp

Encode:
Gui, Submit, NoHide
GuiControl, , Result, % Crypt.Encrypt.String("AES", "CBC", Input, Key, IV)
Return

Decode:
Gui, Submit, NoHide
GuiControl, , Result, % Crypt.Decrypt.String("AES", "CBC", Input, Key, IV)
Return
```

The function to encrypt works well and is compatible with OpenSSL, but the function Crypt.Decrypt.String() does not work, it always gives errors.

How to proceed?

**Comment by jNizM** [comment]
Used compiler shipped with AHK v1.1.35.00 and it works for me

![grafik](https://user-images.githubusercontent.com/2289812/205274491-10f11871-f536-4085-b71a-33ab17e7aa15.png)

Can you post the complete Error Message (maybe as image)
